name: master

on:
    push:
        branches:
            - main

            
env:
    enviroment: test

jobs:
    test:
        uses: ./.github/workflows/test.yml
        with:
            enviroment: ${{github.env.enviroment}}