name: master

on:
    push:
        branches:
            - main

env:
  DAY_OF_WEEK: Monday

jobs:
    test:
        uses: ./.github/workflows/test.yml
        with:
            enviroment: ${{env.DAY_OF_WEEK}}