name: master


env:
    DAY_OF_WEEK: Monday

on:
    pull_request:
        types: [opened,closed]


jobs:
    test:
        uses: ./.github/workflows/test.yml
        with:
            enviroment: ${{github.DAY_OF_WEEK}}