name: test

on:
    workflow_call:
        inputs:
            enviroment:
                required: true
                type: string
                default: aaa

jobs:
    test_job_0:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: test_test
              run:
                echo funciona no merge
    test_job:
        if: ${{github.event.pull_request.state=='closed' && github.event.pull_request.merged==true}}
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: test_test
              run:
                echo funciona merge