name: test

on:
    workflow_call:
        inputs:
            enviroment:
                required: true
                type: string
                default: aaa

jobs:
    test_job:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: test_test
              run:
                echo ${{inputs.enviroment}}